spring:
  main:
    web-application-type: reactive
  application:
    name: api-service
#  cloud:
#    gateway:
#      routes:
#        - id: beneficiary-service
#          uri: http://localhost:8083
#          predicates:
#            - Path=/beneficiaries/**
#        - id: auth-service
#          uri: http://localhost:8089
#          predicates:
#            - Path=/api/auth/**
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 10   # 10 requests per second
#                redis-rate-limiter.burstCapacity: 20   # Allow up to 20 requests in bursts
#                key-resolver: "#{@apiKeyResolver}"     # Key to limit by (e.g., IP or API Key)
#                zipkin:
#                  base-url: http://zipkin-server:9411
#                  enabled: true
#                  sleuth:
#                    sampler:
#                      probability: 1.0		
jwt:
  secret: abcdedfgh
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8088

app:
  jwt-expiration-milliseconds: 604800000
  jwt-secret: h3b6mv05FxOfWOAKhhZe1ymkjdXVOpUCMi/7t/kpZbk=
