datasource:
  url: jdbc:mysql://beneficiary-service-mysql:3306/beneficiary_db
  username: beneficiary_user
  password: beneficiary_pwd
  driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Or use 'create' or 'validate' depending on your needs
    show-sql: true

    management:
      endpoints:
        web:
          exposure:
            include: health,info,prometheus  # Expose the prometheus metrics endpoint
      endpoint:
        health:
          show-details: always
      metrics:
        export:
          prometheus:
            enabled: true
      server:
        port: 8081  # Change this port based on the service
        zipkin:
          base-url: http://zipkin-server:9411
          enabled: true
          sleuth:
            sampler:
              probability: 1.0  # 100% tracing