spring:
  datasource:
    url: jdbc:postgresql://transaction-service-postgres:5432/transaction_db
    username: transaction_user
    password: transaction_pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Or use 'create' or 'validate' depending on your needs
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # Expose the prometheus metrics endpoint
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  server:
    port: 8084  # Change this port based on the service

    resilience4j:
      circuitbreaker:
        instances:
          paymentsService:
            sliding-window-type: TIME_BASED
            sliding-window-size: 100
            failure-rate-threshold: 50
            wait-duration-in-open-state: 10s

            zipkin:
              base-url: http://zipkin-server:9411
              enabled: true
              sleuth:
                sampler:
                  probability: 1.0  # 100% tracing